import { WebClient } from "@slack/web-api";
import type { Block, KnownBlock } from "@slack/web-api";
import type { StandupNote } from "../ai/summarize.js";

export async function postStandupToSlack(
  userToken: string,
  channelId: string,
  notes: StandupNote[],
  title: string,
  date: string
): Promise<void> {
  const client = new WebClient(userToken);

  const blocks: (Block | KnownBlock)[] = [
    {
      type: "header",
      text: {
        type: "plain_text",
        text: `${title} — ${date}`,
        emoji: true,
      },
    },
    {
      type: "divider",
    },
  ];

  for (const note of notes) {
    const hasContent =
      note.yesterday.length > 0 || note.today.length > 0 || note.blockers.length > 0;

    if (!hasContent) continue;

    // Person header
    blocks.push({
      type: "section",
      text: {
        type: "mrkdwn",
        text: `*👤 ${capitalize(note.username)}*`,
      },
    });

    // Yesterday
    if (note.yesterday.length > 0) {
      const items = note.yesterday.map((item) => `• ${item}`).join("\n");
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*✅ Yesterday*\n${items}`,
        },
      });
    }

    // Today
    if (note.today.length > 0) {
      const items = note.today.map((item) => `• ${item}`).join("\n");
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*🔨 Today*\n${items}`,
        },
      });
    }

    // Blockers
    if (note.blockers.length > 0) {
      const items = note.blockers.map((item) => `• ${item}`).join("\n");
      blocks.push({
        type: "section",
        text: {
          type: "mrkdwn",
          text: `*🚧 Blockers*\n${items}`,
        },
      });
    }

    blocks.push({ type: "divider" });
  }

  // Footer
  blocks.push({
    type: "context",
    elements: [
      {
        type: "mrkdwn",
        text: `_Generated by standup-cli • ${new Date().toLocaleTimeString("en-IN", { timeZone: "Asia/Kolkata" })}_`,
      },
    ],
  });

  const result = await client.chat.postMessage({
    channel: channelId,
    blocks,
    text: `${title} — ${date}`, // fallback text for notifications
  });

  if (!result.ok) {
    throw new Error(`Slack API error: ${result.error}`);
  }

  console.log(`✅ Standup posted to Slack for ${notes.length} team member(s)`);
}

function capitalize(str: string): string {
  return str.charAt(0).toUpperCase() + str.slice(1);
}
